spring:
  application:
    name: api-security-case

server:
  port: 8080
  servlet:
    context-path: /security

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    prometheus:
      enabled: true