global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "case-itau"
    metrics_path: /security/actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "case-itau"